name: CI-CD
on: 
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Obtendo o código fonte
        uses: actions/checkout@v3.5.3
        
      - name: Docker Login
        uses: docker/login-action@v2.2.0
        with:
          username: ${{ secrets.DOCKERHUB_USR }}
          password: ${{ secrets.DOCKERHUB_PWD }}
        
      - name: Docker build 
        uses: docker/build-push-action@v4.1.1
        with: 
          context: ./src
          file: ./src/Dockerfile
          push: true
          tags: |
            niltonpita/kube-news:v${{ github.run_number }}
            niltonpita/kube-news:latest
  CD:
    runs-on: ubuntu-latest
    needs: [CI]
    steps: 
        - name: Checkout do repositorio
          uses: actions/checkout@v4.1.0
          
        - name: Configuração da credencial da AWS
          uses: aws-actions/configure-aws-credentials@v4
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}
            aws-region: us-east-1
    
        - name: Install kubectl
          uses: azure/setup-kubectl@v2.0
          with:
            version: 'v1.27.0' # default is latest stable
            id: install
            
        - name: Configurar o KubeConfig
          run: aws eks update-kubeconfig --name testeNT-eks --region us-east-1

        - name: Deploy to Kubernetes cluster
          uses: Azure/k8s-deploy@v4.9
          with:
            manifests: |
              ./kube-news/k8s/deployment.yaml
            images: | 
              niltonpita/kube-news:${{ github.run_number }}
